#Application
spring:
  application:
    name: ssc-asu-disease
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  #Cache
  cache:
    jcache:
      config: classpath:ehcache.xml
#General configuration
server:
  port: 8087
  servlet:
    context-path: /asu/v1/disease
#Logging
#logging:
#  level:
#    root: DEBUG
#Exceptions
disease:
  success: The operation was successful.
  prefix: 'API-DS:'
  error:
    general: There was an unexpected error. Please try again.

